[default]
S3_BUCKET = "your-knowledge-base-bucket"
S3_BUCKET_FOLDER = "your-knowledge-base-bucket-folder"
KNOWLEDGE_BASE_ID = "your-knowledge-base-id"
AGENT_ID = "your-agent-id"
AGENT_ALIAS_ID = "TSTALIASID"
AWS_ACCESS_KEY_ID = "your_access_key_here"
AWS_SECRET_ACCESS_KEY = "your_secret_key_here"
AWS_DEFAULT_REGION = "us-east-1"